#
# Makefile for the accel chip driver.
#

obj-$(CONFIG_ACCEL_SENSORS_KXTF9)	+= kxtf9.o
obj-$(CONFIG_ACCEL_SENSORS_LIS3DH)	+= lis3dh.o
obj-$(CONFIG_ACCEL_SENSORS_LSM330D_A)	+= lsm330d_acc.o
obj-$(CONFIG_ACCEL_SENSORS_MMA845X)	+= mma845x.o