ifeq ($(CONFIG_DEVICE_MAX98095),y)
snd-soc-max9809X-objs := max98095.o 
endif
ifeq ($(CONFIG_DEVICE_MAX98096),y)
snd-soc-max9809X-objs := max98096.o
endif

obj-$(CONFIG_SND_SOC_MAX9809X)	+= snd-soc-max9809X.o